CREATE DATABASE seligaai;

CREATE TABLE aluno(
    matricula VARCHAR(255) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    celular VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

